# rasa_interface.py
import logging
from rasa import __version__ as rasa_version
from rasa.core.agent import Agent
from rasa.nlu.model import Interpreter
from rasa.core.policies import MemoizationPolicy, KerasPolicy
from rasa.core import utils
import os

logging.basicConfig(level=logging.INFO)

class RasaInterface:
    def __init__(self, model_path: str):
        """
        Initializes the RasaInterface with the given model path.
        Args:
            model_path (str): Path to the Rasa model directory.
        """
        self.model_path = model_path
        self.agent = self.load_rasa_agent(model_path)

    def load_rasa_agent(self, model_path):
        """
        Loads the Rasa agent from the provided model path.
        Args:
            model_path (str): The path to the trained Rasa model.
        Returns:
            agent (Agent): A Rasa agent for handling user inputs.
        """
        # Load the interpreter (adjusted for newer versions)
        interpreter = Interpreter.load(model_path)
        
        # Load the agent with the interpreter and policies (keep your policy options)
        agent = Agent.load(model_path, interpreter=interpreter, policies=[MemoizationPolicy(), KerasPolicy()])
        return agent

    def handle_message(self, message: str):
        """
        Handles a user message by passing it to the Rasa agent and returning the response.
        Args:
            message (str): The user input message to process.
        Returns:
            response (str): The response generated by the Rasa model.
        """
        # Get the response from the agent
        responses = self.agent.handle_text(message)
        
        # If Rasa returns any response, pick the first one and return it
        if responses:
            return responses[0]['text']
        else:
            return "Sorry, I didn't understand that."

    def train_online(self, domain_path, training_data_path, config_path, loop=None):
        """
        Trains the Rasa model online.
        Args:
            domain_path (str): Path to the domain.yml file.
            training_data_path (str): Path to the training data (stories, nlu data).
            config_path (str): Path to the configuration file.
            loop (optional): Loop to use for training (usually for incremental training).
        """
        # Ensure the paths exist
        if not os.path.exists(domain_path) or not os.path.exists(training_data_path) or not os.path.exists(config_path):
            logging.error("Missing necessary files for training. Check your paths.")
            return
        
        # Train the model online
        training_data = utils.load_data(training_data_path)
        config = utils.read_yaml(config_path)
        domain = utils.read_yaml(domain_path)

        # You can add online training here as needed
        agent = Agent(domain, policies=[MemoizationPolicy(), KerasPolicy()])
        agent.train(training_data, config)
        agent.persist(self.model_path)
        logging.info("Model trained and saved to {}".format(self.model_path))

    def save_model(self, model_dir):
        """
        Saves the trained model to a specified directory.
        Args:
            model_dir (str): Path to the directory where the model will be saved.
        """
        if not os.path.exists(model_dir):
            os.makedirs(model_dir)
        self.agent.persist(model_dir)
        logging.info("Model saved to {}".format(model_dir))
